/*
 * C FFI Stubs for Austral Compiler
 * These functions bridge C code to OCaml compiler
 */

#define CAML_NAME_SPACE
#include <caml/alloc.h>
#include <caml/callback.h>
#include <caml/fail.h>
#include <caml/memory.h>
#include <caml/mlvalues.h>
#include <caml/alloc.h>
#include <string.h>
#include <stdio.h>

/* Initialize OCaml runtime (call once at startup) */
value austral_init_compiler(value unit) {
    caml_startup(NULL);
    return Val_unit;
}

/* Compile a string to C code (returns string option) */
value austral_compile_to_c(value source) {
    CAMLparam1(source);
    CAMLlocal2(result, opt);
    
    const char *src = String_val(source);
    
    /* Call OCaml function */
    static value *closure = NULL;
    if (closure == NULL) {
        closure = caml_named_value("compile_to_c");
    }
    
    if (closure == NULL) {
        caml_failwith("compile_to_c not found");
    }
    
    result = caml_callback(*closure, source);
    
    /* Result is string option - extract if Some */
    if (Is_block(result)) {
        /* Some(s) -> return string */
        opt = Field(result, 0);
        CAMLreturn(opt);
    } else {
        /* None -> return empty string */
        CAMLreturn(caml_copy_string(""));
    }
}

/* Compile cell module (returns tuple option) */
value austral_compile_cell(value source) {
    CAMLparam1(source);
    CAMLlocal3(result, pair, code);
    
    const char *src = String_val(source);
    
    /* Call OCaml function */
    static value *closure = NULL;
    if (closure == NULL) {
        closure = caml_named_value("compile_cell");
    }
    
    if (closure == NULL) {
        caml_failwith("compile_cell not found");
    }
    
    result = caml_callback(*closure, source);
    
    /* Result is (string * string) option */
    if (Is_block(result)) {
        pair = Field(result, 0);
        code = Field(pair, 0);  /* First element is the code */
        CAMLreturn(code);
    } else {
        CAMLreturn(caml_copy_string(""));
    }
}

/* Helper: Write compiled code to file */
int austral_compile_and_write(const char *source, const char *filename) {
    value src = caml_copy_string(source);
    value result = austral_compile_to_c(src);
    
    const char *code = String_val(result);
    if (strlen(code) == 0) {
        return -1;  // Compilation failed
    }
    
    FILE *fp = fopen(filename, "w");
    if (!fp) return -2;
    
    fprintf(fp, "/* Generated by SafestOS Austral Compiler */\n");
    fprintf(fp, "#include <string.h>\n");
    fprintf(fp, "#include <stdint.h>\n");
    fprintf(fp, "#include \"vm.h\"\n\n");
    fprintf(fp, "%s\n", code);
    
    fclose(fp);
    return 0;
}
